import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { ActionButton, ActionForm } from "@/components/voices/ui";
import { Pill } from "@/components/voices/server";
import { getActor, getVoices, voicesOpen } from "@/lib/voices/context";

export default async function AdminPage() {
  if (!voicesOpen()) return null; // Voices closed: the layout shows "Opening soon"; skip DB reads.
  const [svc, actor] = await Promise.all([getVoices(), getActor()]);
  if (!actor) redirect("/login?next=/voices/admin");
  if (!svc.isAdmin(actor)) notFound();
  const q = await svc.adminQueue(actor);
  const [rec, cfg, purchases, workspaces] = await Promise.all([svc.reconcile(actor), svc.pricing(), svc.repo.find("voice_purchases", {}, { order: "created_at", desc: true, limit: 30 }), svc.repo.find("voice_workspaces")]);
  const { version: _v, active: _a, created_at: _c, ...pricing } = cfg; void _v; void _a; void _c;
  return (
    <div className="space-y-8">
      <h1 className="font-display text-3xl font-extrabold">Voices admin</h1>
      <p className="text-sm">Ledger: {rec.ok ? <Pill tone="green">balanced · {rec.checkedEntries} entries</Pill> : <Pill tone="amber">{rec.issues.length} issue(s)</Pill>} {rec.issues.map((i) => <span key={i} className="block text-xs text-amber-200">{i}</span>)} <ActionButton action="admin.release" body={{}} label="Release matured earnings" /></p>
      <section className="card space-y-3 p-5"><h2 className="font-display text-lg font-bold">Verification & review queue ({q.voices.length})</h2>
        {q.voices.length === 0 && <p className="text-sm text-ink-3">Nothing waiting.</p>}
        {q.voices.map((v) => <div key={v.id} className="space-y-2 rounded-lg border border-white/10 p-3 text-sm"><p><Link href={`/voices/${v.slug}`} className="font-bold text-cyan">{v.display_name}</Link> · {v.status.replace(/_/g, " ")} · {v.verification_status.replace(/_/g, " ")}</p>
          {!v.is_demo && <ActionForm compact action="admin.link-provider" extra={{ voiceId: v.id }} submit="Link ElevenLabs voice" fields={[{ name: "ref", label: "ElevenLabs voice id shared by the creator", type: "text", required: true }]} />}
          <ActionForm compact action="admin.verify" extra={{ voiceId: v.id, passed: true }} submit="Mark manually verified" fields={[{ name: "notes", label: "How you verified (voice matches consent recording, ID…)", type: "text", required: true }]} />
          <div className="flex gap-2"><ActionButton action="admin.review" body={{ voiceId: v.id, decision: "approved" }} label="Approve listing" variant="primary" /><ActionButton action="admin.review" body={{ voiceId: v.id, decision: "changes_requested" }} label="Request changes" /><ActionButton action="admin.review" body={{ voiceId: v.id, decision: "rejected" }} label="Reject" /></div></div>)}
      </section>
      <section className="card space-y-3 p-5"><h2 className="font-display text-lg font-bold">Dialect review ({q.dialect.length})</h2><p className="text-xs text-ink-3">Must be done by a native speaker of the dialect.</p>
        {q.dialect.map((v) => <div key={v.id} className="rounded-lg border border-white/10 p-3 text-sm"><p className="mb-2 font-bold">{v.display_name} <span className="font-normal text-ink-3">{v.dialects.join(", ")}</span></p><ActionForm compact action="admin.dialect" extra={{ voiceId: v.id, decision: "approved" }} submit="Approve dialect" fields={[{ name: "nativeSpeakerOf", label: "Reviewer is native speaker of", type: "text", required: true }]} /></div>)}</section>
      <section className="card space-y-2 p-5"><h2 className="font-display text-lg font-bold">Samples awaiting approval ({q.samples.length})</h2>{q.samples.map((s) => <div key={s.id} className="flex items-center justify-between text-sm"><span>{s.title}</span><span className="flex gap-2"><ActionButton action="admin.sample" body={{ sampleId: s.id, approve: true }} label="Approve" /><ActionButton action="admin.sample" body={{ sampleId: s.id, approve: false }} label="Hide" /></span></div>)}</section>
      <section className="card space-y-2 p-5"><h2 className="font-display text-lg font-bold">Reports ({q.reports.length})</h2>{q.reports.map((r) => <div key={r.id} className="flex flex-wrap items-center justify-between gap-2 text-sm"><span>{r.reason}: <span dir="auto">{r.details}</span></span><span className="flex gap-2"><ActionButton action="admin.report" body={{ reportId: r.id, action: "actioned", suspend: true }} label="Suspend voice" confirm="Suspend this voice?" /><ActionButton action="admin.report" body={{ reportId: r.id, action: "dismissed" }} label="Dismiss" /></span></div>)}</section>
      <section className="card space-y-2 p-5"><h2 className="font-display text-lg font-bold">All voices</h2>{q.all.map((v) => <div key={v.id} className="flex items-center justify-between text-sm"><span>{v.display_name} · {v.status}</span>{v.status === "suspended" ? <ActionButton action="admin.reinstate" body={{ voiceId: v.id }} label="Reinstate" /> : v.status === "active" ? <ActionForm compact action="admin.suspend" extra={{ voiceId: v.id }} submit="Suspend" fields={[{ name: "reason", label: "Reason", type: "text", required: true }]} /> : null}</div>)}</section>
      <section className="card space-y-2 p-5"><h2 className="font-display text-lg font-bold">Recent purchases</h2>{purchases.map((p) => <div key={p.id} className="flex flex-wrap items-center justify-between gap-2 text-sm"><Link href={`/voices/receipts/${p.id}`} className="text-cyan">{p.terms_snapshot.voice.display_name} · {p.price_ixis} Ixis · {p.status}</Link>{p.status === "fulfilled" && <ActionForm compact action="admin.refund" extra={{ purchaseId: p.id }} submit="Refund as credit" fields={[{ name: "reason", label: "Reason", type: "text", required: true }]} />}</div>)}</section>
      <div className="grid gap-6 md:grid-cols-2">
        <section className="card space-y-3 p-5"><h2 className="font-display text-lg font-bold">Invite</h2><ActionForm action="admin.invite" submit="Invite" fields={[{ name: "email", label: "Email", type: "email", required: true }, { name: "role", label: "Role", type: "select", options: [{ value: "both", label: "Customer + creator" }, { value: "customer", label: "Customer" }, { value: "creator", label: "Creator" }] }]} /></section>
        <section className="card space-y-3 p-5"><h2 className="font-display text-lg font-bold">Grant plan allowance (manual)</h2><ActionForm action="admin.allowance" submit="Grant" fields={[{ name: "workspaceId", label: "Workspace", type: "select", options: workspaces.map((w) => ({ value: w.id, label: w.name })) }, { name: "packageId", label: "Plan", type: "select", options: [{ value: "solo_monthly", label: "Solo monthly (8)" }, { value: "label_enterprise", label: "Label / Enterprise (50)" }] }, { name: "units", label: "Voiceovers", type: "number", defaultValue: 8 }, { name: "note", label: "Note (e.g. Wallet receipt)", type: "text", required: true }]} /></section>
        <section className="card space-y-3 p-5 md:col-span-2"><h2 className="font-display text-lg font-bold">Pricing (v{cfg.version}{cfg.illustrative ? ", illustrative" : ""})</h2><p className="text-xs text-ink-3">Saving creates a new version. Existing receipts keep their frozen price.</p>
          <ActionForm action="admin.pricing" extra={{ ...pricing }} submit="Save new pricing version" fields={[{ name: "payg_base_ixis", label: "PAYG base (Ixis)", type: "number", defaultValue: cfg.payg_base_ixis }, { name: "payg_step_ixis", label: "Per extra step (Ixis)", type: "number", defaultValue: cfg.payg_step_ixis }, { name: "audition_ixis", label: "Paid audition (Ixis)", type: "number", defaultValue: cfg.audition_ixis }, { name: "free_auditions_per_day", label: "Free auditions / business / day", type: "number", defaultValue: cfg.free_auditions_per_day }, { name: "custom_min_ixis", label: "Custom recording minimum", type: "number", defaultValue: cfg.custom_min_ixis }, { name: "illustrative", label: "Still illustrative", type: "checkbox", defaultChecked: cfg.illustrative }]} /></section>
      </div>
    </div>
  );
}
